---
stages:
  - build

variables:
  GIT_STRATEGY: empty

init sans bootstrap :
  stage: build
  tags:
    - windows
    - amd64
  
  script:
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) gallus_download_tools"

build sans init :
  stage: build
  tags:
    - windows
    - amd64
  
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -build"




bootstrap:
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - if [ -d -path "C:\Gallus" ]; remove-item -path "C:\Gallus" -recurse -force
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -full -o C:\\Gallus\\GMedia\\LiteTouchMedia.iso"
  artifacts:
    paths:
      - C:/Gallus/GMedia/LiteTouchMedia.iso
    expire_in: 3 days
    
   
test iso:
  stage: build
  tags:
    - windows
    - amd64
  dependencies:
    - bootstrap
  script: 
    - if file C:\Gallus\GMedia\LiteTouchMedia.iso | grep "ISO 9660"  > /dev/null exit 0
    - else exit 1