---
bootstrap:
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - if [ -d -path "C:\Gallus" ]; remove-item -path "C:\Gallus" -recurse -force
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -full"
    - cd \Gallus\GMedia\
    - $isoPath = "C:\Gallus\GMedia\LiteTouchMedia.iso"
    - if (-not (test-path $isoPath)) {write-output "fichier n'existe pas" ; exit 2 } 
    - $fs=[System.IO.File]::OpenRead($isoPath)
    - $fs.Seek(32769, [System.IO.SeekOrigin]::Begin) | Out-Null; $buffer=New-Object byte[] 5
    - $fs.Read($buffer, 0, 5) | Out-Null
    - $fs.Close()
    - $signature = [System.Text.Encoding]::ASCII.GetString($buffer)
    - $fs.Close()
    - if ($signature -eq "CD001") { write-output "L'iso est un 9660" ; exit 0} else {wirte-output "Le fichier n'est pas un iso 9660" ; exit 1}

  
Montage de l'iso:
  stage: build
  tags:
    - windows
    - amd64
  script:
    - cd .\Gallus\GMedia\
    - .\LiteTouchMedia.iso
    - $isom =Get-Volume | where-object { $_.filesystem -eq "UDF"} | Select-Object -ExpandProperty DriveLetter | oss
    - cd -join($isom, ":")
    - exit 0
  after_script:
    - $driveEject.NameSpace(17).ParseName(-join ($isom, ":")).InvokeVerb("Eject")
  




  #artifacts:
   # paths:
    #  - C:/Gitlab-Runner/builds/t1_81duzo/0/gallus/core-empty/giso.iso
    #expire_in: 3 days
    
   
#test iso:
#  stage: build
#  tags:
#    - windows
#    - amd64
#  dependencies:
#    - bootstrap
#  script: 



stages:
  - build

variables:
  GIT_STRATEGY: empty

init sans bootstrap :
  stage: build
  tags:
    - windows
    - amd64
  
  script:
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) gallus_download_tools"

build sans init :
  stage: build
  tags:
    - windows
    - amd64
  
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -build"



