---
stages:
  - build

variables:
  GIT_STRATEGY: empty

init dans gallus :
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - remove-item -path "C:\Gallus" -recurse -force
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) gallus_download_tools"





bootstrap:
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - remove-item -path "C:\Gallus" -recurse -force
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -full"
    
