---
stages:
  - linter
  - build

variables:
  GIT_STRATEGY: empty

default:
  tags:
    - amd64
    - windows

installGit:
  stage: build
  script: |
    winget install --silent --id Git.Git --exact --source winget
    ! (& "C:\Program Files\Git\cmd\git.exe")

verifCode:
  stage: build
  before_script: |
    if (Test-Path -PathType Container -Path C:\gallus-code") { Remove-item -Path C:\gallus-code -recurse -force }
    Install-Module -Name PSScriptAnalyzer -Force
    & "C:\Program Files\Git\cmd\git.exe" clone https://github.com/Eternilab/gallus C:\gallus-code
  script: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-ScriptAnalyzer -path C:\gallus-code
  after_script: |
    Remove-item -path C:\Gallus-code -recurse -force
