---
stages:
  - build

variables:
  GIT_STRATEGY: empty

init sans bootstrap :
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - if [ -d "Gallus" ]; remove-item -path "C:\Gallus" -recurse -force
  allow_failure : true
  script:
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) gallus_download_tools"

build sans init :
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - if [ -d -path "C:\Gallus" ]; remove-item -path "C:\Gallus" -recurse -force
  allow_failure: true
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - ! "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -build"


test iso:
  stage: build
  tags:
    - windows
    - amd64
  script:
    - |
      $isofile = "LiteTouchMedia.iso";
      if (C:\Gallus\GMedia\ $isoFile) {
        write-output "le fichier est introuvable"
        exit 1
      }

      $bytes = get-content -path $isofile -encoding byte -totalcount 32769
      if (&byte[32769-5] -eq 0x43 -and $bytes[32769-4] -eq 0x44 -and $bytes[32769-3] -eq 0x30 -and $bytes[32769-2] -eq 0x30 -and $bytes[32769-1] -eq 0x31) {
          write-output "bon fichier"
          }else {
            write-output "pas bon fichier"
            exit 1
            }





bootstrap:
  stage: build
  tags:
    - windows
    - amd64
  before_script:
    - if [ -d -path "C:\Gallus" ]; remove-item -path "C:\Gallus" -recurse -force
  script:
    - New-Item -ItemType Directory -Force -Path "\Gallus"
    - cd \Gallus
    - Set-ExecutionPolicy Bypass -Scope Process -Force
    - "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -oneliner"
    - "& ([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Eternilab/gallus/main/gallus.ps1'))) -full"
    
    
    
    
    
