#----------------------------------------------------------------------------
#    Copyright (C) 2024 Eternilab <support@eternilab.com>
#
#    Author: Dionys Colson <dionys.colson@eternilab.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#----------------------------------------------------------------------------

# This file contains all necessary variables for "AuditingScript.ps1" and "CopyAuditingFiles.ps1".

# ----- Variables for multiple scripts

# Desktop by default
$TargetPath = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::Desktop) + "\GallusAuditReport\"

$CssFile = "$TargetPath\ReportStyle.css"
$JsModuleFile = "$TargetPath\tsorter.min.js"
$JsFile = "$TargetPath\ReportScript.js"

$HtmlFooter = "</div><script src=$($JsModuleFile)></script><script src=$($JsFile)></script>"

$EternilabLogo = "$TargetPath\Eternilab.png"

# ----- Variables for the CopyAuditingFiles script

$SourcePath = ".\"

$CopyFilesList = (
"Eternilab.png",
"ReportScript.js", 
"ReportStyle.css",
"tsorter.min.js"
)


# ----- Variables for the AuditingScript script

$HKModule = ".\HardeningKitty.psm1"

$findinglist = ".\finding_list_cis_microsoft_windows_11_enterprise_22h2_machine.csv"

$HKLogOutputFile = "$TargetPath\Auditreport.txt"
$HKCsvOutputFile = "$TargetPath\AuditReport.csv"

$ReportHtmlTitle = "Hardening Kitty Audit Report"
$ReportHtmlOutputFile = "$TargetPath\AuditReport.html"
$ReportHeader = "<div class='header'><div class='header-left'><h1>Gallus Audit Report</h1>`n<h5>Generated by <strong>Hardening Kitty</strong> on $(Get-Date)</h5></div><div class='header-right'><img src='$($EternilabLogo)' width='512px' height='120px'></div></div><div class='tablecontainer'>"


# ----- Variables for the GenerateGHITable Script

$GhiCsvFile = ".\GHI.csv"

$GhiHtmlTitle = "Gallus GHI Table"
$GhiHtmlOutputFile = "$TargetPath\GHI.html"
$GhiHeader = "<div class='header'><div class='header-left'><h1>Gallus GHI</h1>`n<h5>à date du $(Get-Date)</h5></div><div class='header-right'><img src='$($EternilabLogo)' width='512px' height='120px'></div></div><div class='tablecontainer'>"
