#----------------------------------------------------------------------------
#    Copyright (C) 2024 Eternilab <support@eternilab.com>
#
#    Author: Dionys Colson <dionys.colson@eternilab.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#----------------------------------------------------------------------------

# This file contains all necessary variables for "AuditingScript.ps1" and "CopyAuditingFiles.ps1".

# ----- Functions & Variables for multiple scripts

# Desktop by default
$TargetPath = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::Desktop) + "\GallusAuditReport\"

$CssFile = "$TargetPath\ReportStyle.css"
$JsFile = "$TargetPath\ReportScript.js"

$HtmlFooter = "</div><script src=$($JsFile)></script>"

$Charset = "ISO-8859-1"

$EternilabLogo = "$TargetPath\Eternilab.png"

function Generate-Header {

    param( [string]$Title, [string]$Subtitle )

    return @"
<div class='header'>
    <div class='header-left'>
        <h1>$($Title)</h1>
        <h5>$($Subtitle)</h5>
    </div>
    <div class='header-right'>
        <img alt='Eternilab logo' src='$($EternilabLogo)' width='512px' height='120px'>
    </div>
</div>
<div class='tablecontainer'>
"@

}

# ----- Variables for the CopyAuditingFiles script

$SourcePath = ".\"

$CopyFilesList = (
"Eternilab.png",
"ReportScript.js",
"ReportStyle.css"
)

# ----- Variables for the AuditingScript script

$HKModule = ".\HardeningKitty.psm1"

$findinglist = ".\finding_list_cis_microsoft_windows_11_enterprise_23h2_machine.csv"

$HKLogOutputFile = "$TargetPath\Auditreport.txt"
$HKCsvOutputFile = "$TargetPath\AuditReport.csv"

$ReportHtmlTitle = "Hardening Kitty Audit Report"
$ReportHtmlOutputFile = "$TargetPath\AuditReport.html"
$ReportHeader = Generate-Header -Title "Gallus Audit Report" -Subtitle "Generated by <strong>Hardening Kitty</strong> on $(Get-Date -UFormat '%d/%m/%Y %R:%S')"

# ----- Variables for the GenerateGHITable Script

$GhiCsvFile = ".\GHI.csv"

$GhiHtmlTitle = "Gallus GHI Table"
$GhiHtmlOutputFile = "$TargetPath\GHI.html"
$GhiHeader = Generate-Header -Title "Gallus GHI" -Subtitle "à date du $(Get-Date -UFormat '%d/%m/%Y %R:%S')"
